[supervisord]
nodaemon=true
user=root
logfile=/var/log/project/supervisord.log
logfile_maxbytes=50MB
logfile_backups=0
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/project
loglevel=info

[program:django]
command=gunicorn project.wsgi:application --bind 0.0.0.0:3000 --workers 4 --threads 2 --timeout 120 --access-logfile - --error-logfile -
directory=/app
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/project/django.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=0
stopwaitsecs=60
priority=1

[program:celery-worker]
command=celery -A services worker -l info
directory=/app
user=root
autostart=true
autorestart=true
environment=PROCESS_TYPE="celery-worker"
redirect_stderr=true
stdout_logfile=/var/log/project/celery-worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=0
stopwaitsecs=60
priority=2

[program:cron]
command=supercronic /app/crontab
directory=/app
user=root
autostart=true
autorestart=true
environment=PROCESS_TYPE="cron"
redirect_stderr=true
stdout_logfile=/var/log/project/cron.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=0
stopwaitsecs=60
priority=3

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/project/nginx.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=0
stopwaitsecs=60
priority=4
