# Generated by Django 6.0.6 on 2026-06-13 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CronJobExecution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.IntegerField(
                        choices=[(10, "Celery Task"), (20, "Management Command")],
                        default=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(10, "Running"), (20, "Success"), (30, "Failed")],
                        default=10,
                    ),
                ),
                ("is_successful", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(default=datetime.datetime.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("output", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                ("executed_by", models.CharField(default="crontab", max_length=50)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["job_type", "name", "-started_at"],
                        name="manager_cro_job_typ_32a86b_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="manager_cro_status_edc0d9_idx",
                    ),
                ],
            },
        ),
    ]
